version: '3.8'
name: ts-express-api

services:
  nodejs:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    working_dir: /app
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_COLLECTION=db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=secret
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_QUEUE=queue
    depends_on:
      - redis
      - rabbitmq
      - mongodb

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=secret

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
