#deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-express-api
  labels:
    app: ts-express-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-express-api
  template:
    metadata:
      labels:
        app: ts-express-api
    spec:
      containers:
      - name: ts-express-api
        image: ts-express-api:latest
        ports:
        - containerPort: 7860 
        envFrom:
        - configMapRef:
            name: ts-express-api-config